// GENERATED by ai-team. Do not edit: change the team rows and regenerate.
//
// This seat has a connection, so eve's default tools are on - `connection_search` is one
// of them and is the only route to a connection. That also brings back web access, which
// this withholds.
//
// Not a bandwidth concern: a fetched page is untrusted text landing in the model's
// context, and the work a seat needs is in its worktree, its plan and its connections.
// Disabling is legal here precisely because the framework default exists underneath;
// at a slot with nothing under it, `disableTool()` is a build error.

import { disableTool } from "eve/tools";

export default disableTool();
