// GENERATED by ai-team. Do not edit: change the team rows and regenerate.
//
// This seat is read-only, and eve's default tools are on because it needs a framework
// default - `connection_search` for a connection, `load_skill` for the repository's
// skills. Turning the defaults on brings back eve's own `write_file`, which a read-only
// seat must not be offered.
//
// It writes to eve's sandbox rather than the worktree, so leaving it would not let this
// seat edit source. The reason to withhold it anyway is that a read-only seat holding a
// tool called `write_file` is a seat that will try to use it, then report work it never
// did - and "cannot edit source" should not depend on the reader knowing which
// filesystem a tool points at.
//
// Legal here precisely because the framework default exists underneath; at a slot with
// nothing under it, `disableTool()` is a build error - which is why `edit_file`, which
// eve has no default for, is withheld by omitting the file instead.

import { disableTool } from "eve/tools";

export default disableTool();
