// GENERATED by ai-team. Do not edit: change the team rows and regenerate.
//
// eve has no default edit tool; this is ai-team's. It refuses an ambiguous match rather
// than replacing the first of several identical blocks, which is how an agent silently
// changes the wrong one.

import { defineTool } from "eve/tools";
import { z } from "zod";

import { editWorktreeFile } from "../lib/tools.js";

const inputSchema = z.object({
  path: z.string().min(1),
  oldText: z.string().min(1),
  newText: z.string(),
  replaceAll: z.boolean().optional(),
});

export const bridgedTool = {
  description:
    "Replace an exact block of text in a file in the leased worktree. oldText must " +
    "match exactly and must be unique unless replaceAll is set.",
  inputSchema,
  async execute(input: z.infer<typeof inputSchema>) {
    return await editWorktreeFile(input);
  },
};

export default defineTool({
  ...bridgedTool,
  label: { start: ({ path }) => `edit ${path}` },
});
