// GENERATED by ai-team. Do not edit: change the team rows and regenerate.
//
// Reads the plan back as markdown, so a seat can see the board it is working from.

import { defineTool } from "eve/tools";
import { z } from "zod";

import { readPlan } from "../lib/plan.js";

export const bridgedTool = {
  description: "Read the current plan: its slices, decisions, gotchas and open questions.",
  inputSchema: z.object({}),
  async execute() {
    return await readPlan();
  },
};

export default defineTool({
  ...bridgedTool,
  label: { start: () => "read the plan" },
});
