// GENERATED by ai-team. Do not edit: change the team rows and regenerate.
//
// Appends to ai-planner's progress log, which is append-only and cannot conflict.

import { defineTool } from "eve/tools";
import { z } from "zod";

import { addNote } from "../lib/plan.js";

const inputSchema = z.object({
  note: z.string().min(1),
  slice: z.string().optional().describe("The slice this is about, if it is about one."),
});

export const bridgedTool = {
  description:
    "Record something the next session needs to know. Write it when it happens rather " +
    "than saving it up - the log is append-only and cannot conflict.",
  inputSchema,
  async execute(input: z.infer<typeof inputSchema>) {
    return await addNote(input.note, input.slice);
  },
};

export default defineTool({
  ...bridgedTool,
  label: { start: ({ note }) => `note: ${note.slice(0, 60)}` },
});
