// GENERATED by ai-team. Do not edit: change the team rows and regenerate.
//
// Writes one slice into ai-planner, the work graph ai-team does not own (D4).

import { defineTool } from "eve/tools";
import { z } from "zod";

import { addSlice } from "../lib/plan.js";

const inputSchema = z.object({
  key: z.string().min(1).describe("Short handle, e.g. PR1 or S2. Unique within the plan."),
  title: z.string().min(1),
  scope: z.string().min(1).describe("What this slice changes, in a sentence or three."),
  demo: z.string().min(1).describe("How a human proves it works."),
  touches: z
    .array(z.string().min(1))
    .min(1)
    .describe(
      "The paths this slice changes, e.g. crates/** or ui/src/App.tsx. Required: the " +
        "slice is dispatched to the seat whose zone owns them.",
    ),
  files: z.number().int().min(1).optional().describe("Rough file count."),
});

export const bridgedTool = {
  description:
    "Add a vertical slice to the plan. Each slice must be small enough to demo on its " +
    "own, and must name the paths it touches so it can be routed to a seat.",
  inputSchema,
  async execute(input: z.infer<typeof inputSchema>) {
    return await addSlice(input);
  },
};

export default defineTool({
  ...bridgedTool,
  label: { start: ({ key, title }) => `plan ${key}: ${title}` },
});
