// GENERATED by ai-team. Do not edit: change the team rows and regenerate.
//
// Replaces eve's sandbox `read_file` at the same slot (D3).

import { defineTool } from "eve/tools";
import { z } from "zod";

import { readWorktreeFile } from "../lib/tools.js";

export default defineTool({
  description:
    "Read a text file from the leased worktree, with line numbers. Paths are relative " +
    "to the worktree root.",
  inputSchema: z.object({
    path: z.string().min(1),
    offset: z.number().int().min(0).optional().describe("First line to return, 0-based."),
    limit: z.number().int().min(1).optional().describe("How many lines to return."),
  }),
  label: { start: ({ path }) => `read ${path}` },
  async execute(input) {
    return await readWorktreeFile(input);
  },
});
