// GENERATED by ai-team. Do not edit: change the team rows and regenerate.
//
// Replaces eve's sandbox `read_file` at the same slot (D3).

import { defineTool } from "eve/tools";
import { z } from "zod";

import { readWorktreeFile } from "../lib/tools.js";

const inputSchema = z.object({
  path: z.string().min(1),
  offset: z.number().int().min(0).optional().describe("First line to return, 0-based."),
  limit: z.number().int().min(1).optional().describe("How many lines to return."),
});

export const bridgedTool = {
  description:
    "Read a text file from the leased worktree, with line numbers. Paths are relative " +
    "to the worktree root.",
  inputSchema,
  async execute(input: z.infer<typeof inputSchema>) {
    return await readWorktreeFile(input);
  },
};

export default defineTool({
  ...bridgedTool,
  label: { start: ({ path }) => `read ${path}` },
});
