// GENERATED by ai-team. Do not edit: change the team rows and regenerate.
//
// Replaces eve's sandbox `write_file` at the same slot (D3). Only generated for seats
// that are allowed to write - a read-only seat gets no file in this slot.

import { defineTool } from "eve/tools";
import { z } from "zod";

import { writeWorktreeFile } from "../lib/tools.js";

const inputSchema = z.object({
  path: z.string().min(1),
  content: z.string(),
});

export const bridgedTool = {
  description:
    "Write a complete file in the leased worktree, creating parent directories as " +
    "needed. To change part of an existing file, prefer edit_file.",
  inputSchema,
  async execute(input: z.infer<typeof inputSchema>) {
    return await writeWorktreeFile(input);
  },
};

export default defineTool({
  ...bridgedTool,
  label: { start: ({ path }) => `write ${path}` },
});
