// GENERATED by ai-team. Do not edit: change the team rows and regenerate.
//
// Replaces eve's sandbox `write_file` at the same slot (D3). Only generated for seats
// that are allowed to write - a read-only seat gets disableTool() here instead.

import { defineTool } from "eve/tools";
import { z } from "zod";

import { writeWorktreeFile } from "../lib/tools.js";

export default defineTool({
  description:
    "Write a complete file in the leased worktree, creating parent directories as " +
    "needed. To change part of an existing file, prefer edit_file.",
  inputSchema: z.object({
    path: z.string().min(1),
    content: z.string(),
  }),
  label: { start: ({ path }) => `write ${path}` },
  async execute(input) {
    return await writeWorktreeFile(input);
  },
});
