// GENERATED by ai-team. Do not edit: change the team rows and regenerate.
//
// The HTTP surface ai-team drives this agent through.
//
// eve's own default policy refuses an unauthenticated caller on /eve/v1/info and every
// session route, which is correct - the port is loopback, but on a shared machine every
// local process can reach loopback, and this API can run shell commands in a real
// checkout.
//
// So the policy is a shared secret that ai-team mints per supervised process and passes
// in the environment, the same way it passes the worktree.
//
// The secret is read per request rather than at module scope, and that is not a style
// choice: `eve build` EVALUATES every authored module, so a module-scope throw for a
// missing variable fails the build on any machine that is not currently running an
// agent. Reading it inside the handler keeps the build hermetic and still fails closed -
// no secret in the environment means no request is ever authorized.

import { verifyHttpBasic } from "eve/channels/auth";
import { eveChannel } from "eve/channels/eve";

export default eveChannel({
  auth: [
    (request: Request) => {
      const password = process.env.AI_TEAM_EVE_TOKEN;
      // Fail closed. An agent whose supervisor forgot the secret serves nobody, rather
      // than serving everybody.
      if (!password) return null;

      // Constant-time comparison, so a local process cannot recover the secret from how
      // long the rejection took.
      const result = verifyHttpBasic(request.headers.get("authorization"), {
        username: "ai-team",
        password,
      });
      // An AuthFn returns the caller's identity, or null to refuse. The verifier's
      // {ok} wrapper is the lower-level shape and is not what the route wants.
      return result.ok ? result.sessionAuth : null;
    },
  ],
});
