// The plan tools, driving ai-planner's own `aip` CLI (D4).
//
// GENERATED by ai-team. Do not edit: change the team rows and regenerate.
//
// ai-planner owns the work graph. It is reached over its command line and not as an eve
// connection, because `aip serve` speaks MCP over stdio while `defineMcpClientConnection`
// requires an HTTP url - so there is no connection to define.
//
// Everything here runs against $AI_TEAM_PLAN_ROOT, the checkout the run belongs to, not
// the leased worktree: a lease is a copy, and a plan written inside one would be a plan
// nobody finds again.

import { spawn } from "node:child_process";

const TIMEOUT_MS = 30_000;

function planRoot(): string {
  // Read per call, not at module scope: `eve build` evaluates every authored module, so
  // a throw up here would fail the build on any machine that is not running an agent.
  const root = process.env.AI_TEAM_PLAN_ROOT;
  if (!root) {
    throw new Error(
      "AI_TEAM_PLAN_ROOT is not set. ai-team sets it on the agent process; running this " +
        "tool outside a supervised run is not supported.",
    );
  }
  return root;
}

function planSlug(): string | undefined {
  return process.env.AI_TEAM_PLAN_SLUG || undefined;
}

async function aip(args: string[]): Promise<string> {
  const root = planRoot();
  const slug = planSlug();
  // `-C` rather than a chdir: several agents share this process tree, and one global
  // working directory would be a race between them.
  const argv = ["-C", root, ...(slug ? ["-p", slug] : []), ...args];

  return await new Promise<string>((settle, fail) => {
    const child = spawn("aip", argv, { cwd: root, stdio: ["ignore", "pipe", "pipe"] });
    let stdout = "";
    let stderr = "";
    const timer = setTimeout(() => {
      child.kill("SIGKILL");
      fail(new Error(`\`aip ${args.join(" ")}\` timed out`));
    }, TIMEOUT_MS);

    child.stdout.on("data", (chunk) => (stdout += String(chunk)));
    child.stderr.on("data", (chunk) => (stderr += String(chunk)));
    child.on("error", (error) => {
      clearTimeout(timer);
      fail(new Error(`could not run \`aip\`: ${error.message}`));
    });
    child.on("close", (code) => {
      clearTimeout(timer);
      if (code === 0) settle(stdout.trim());
      else fail(new Error(`\`aip ${args.join(" ")}\` failed: ${stderr.trim() || `exit ${code}`}`));
    });
  });
}

export type AddSliceInput = {
  key: string;
  title: string;
  scope: string;
  demo: string;
  touches: string[];
  files?: number;
};

/**
 * Add one vertical slice.
 *
 * `touches` is not decoration: ai-team routes a slice to the seat whose zone owns those
 * paths, and a slice that names none cannot be dispatched to anybody. It is appended to
 * the scope as a `Touches:` line so it shows up on the board a human reads, rather than
 * hiding in a side-channel.
 */
export async function addSlice({ key, title, scope, demo, touches, files }: AddSliceInput) {
  const paths = touches.map((path) => path.trim()).filter((path) => path.length > 0);
  if (paths.length === 0) {
    throw new Error(
      `slice ${key} names no paths. Say which files it touches so it can be routed to the ` +
        `seat that owns them.`,
    );
  }
  const scopeWithPaths = `${scope.trim()}\n\nTouches: ${paths.join(", ")}`;

  const args = ["slice", "add", key, title, "--scope", scopeWithPaths, "--demo", demo];
  if (files !== undefined) args.push("--files", String(files));
  await aip(args);
  return { key, title, touches: paths };
}

export async function addNote(note: string, slice?: string) {
  await aip(slice ? ["log", note, "--slice", slice] : ["log", note]);
  return { recorded: note };
}

export async function readPlan() {
  // `--plain` because the rendered form is for a terminal, not for a model.
  const markdown = await aip(["show", "--plain"]);
  return { markdown };
}
