// The authored tools, acting on the leased worktree rather than eve's sandbox (D3).
//
// GENERATED by ai-team. Do not edit: change the team rows and regenerate.
//
// eve's defaults (`bash`, `read_file`, `write_file`) operate on its sandbox. These
// replace them at the same slots, so the model sees familiar names doing the right
// thing rather than a second, parallel set it has to be told to prefer.

import { spawn } from "node:child_process";
import { mkdir, readFile, stat, writeFile } from "node:fs/promises";
import { dirname, relative } from "node:path";

import { resolveInside, worktreeRoot } from "./worktree.js";

/** Output beyond this is truncated; a runaway build log must not become the context. */
const MAX_OUTPUT = 60_000;
const DEFAULT_TIMEOUT_MS = 120_000;

/**
 * The interpreter for `bash`.
 *
 * Named explicitly rather than taken from $SHELL: the login shell is zsh on macOS and
 * bash on Linux, and a command written for one that silently runs under the other is
 * the kind of difference that only shows up in the output. `/bin/sh` is POSIX on both.
 */
const SHELL = "/bin/sh";

export type BashInput = { command: string; timeoutMs?: number };

export async function runBash({ command, timeoutMs }: BashInput) {
  const cwd = worktreeRoot();
  const limit = Math.min(Math.max(timeoutMs ?? DEFAULT_TIMEOUT_MS, 1_000), 600_000);

  return await new Promise<{
    stdout: string;
    stderr: string;
    exitCode: number;
    timedOut: boolean;
    cwd: string;
  }>((settle) => {
    const child = spawn(SHELL, ["-c", command], {
      cwd,
      // A clean-ish environment, plus the worktree so a nested tool agrees with us.
      env: { ...process.env, PWD: cwd },
      stdio: ["ignore", "pipe", "pipe"],
    });

    let stdout = "";
    let stderr = "";
    let timedOut = false;

    const timer = setTimeout(() => {
      timedOut = true;
      // SIGTERM first so the command can clean up; SIGKILL if it will not go.
      child.kill("SIGTERM");
      setTimeout(() => child.kill("SIGKILL"), 5_000).unref();
    }, limit);

    child.stdout.on("data", (chunk) => {
      stdout = append(stdout, String(chunk));
    });
    child.stderr.on("data", (chunk) => {
      stderr = append(stderr, String(chunk));
    });

    child.on("error", (err) => {
      clearTimeout(timer);
      settle({ stdout, stderr: `${stderr}${err.message}`, exitCode: -1, timedOut, cwd });
    });
    child.on("close", (code, signal) => {
      clearTimeout(timer);
      settle({
        stdout,
        stderr,
        // A signalled process reports no code; -1 is clearer than null to the model.
        exitCode: code ?? -1,
        timedOut: timedOut || signal === "SIGKILL" || signal === "SIGTERM",
        cwd,
      });
    });
  });
}

function append(buffer: string, chunk: string): string {
  if (buffer.length >= MAX_OUTPUT) return buffer;
  const room = MAX_OUTPUT - buffer.length;
  return chunk.length <= room
    ? buffer + chunk
    : `${buffer}${chunk.slice(0, room)}\n… output truncated at ${MAX_OUTPUT} characters`;
}

export type ReadInput = { path: string; offset?: number; limit?: number };

export async function readWorktreeFile({ path, offset, limit }: ReadInput) {
  const resolved = resolveInside(path);
  const info = await stat(resolved);
  if (info.isDirectory()) {
    throw new Error(`${path} is a directory`);
  }

  const text = await readFile(resolved, "utf8");
  const lines = text.split("\n");
  const start = Math.max(offset ?? 0, 0);
  const end = limit === undefined ? lines.length : Math.min(start + limit, lines.length);
  const slice = lines.slice(start, end);

  return {
    path: relative(worktreeRoot(), resolved) || ".",
    // Line numbers so the model can cite one, and so an edit can be anchored.
    content: slice.map((line, i) => `${start + i + 1}\t${line}`).join("\n"),
    totalLines: lines.length,
    truncated: end < lines.length || start > 0,
  };
}

export type WriteInput = { path: string; content: string };

export async function writeWorktreeFile({ path, content }: WriteInput) {
  const resolved = resolveInside(path);
  // Creating the parent is the common case for a new module, and failing on it would
  // only teach the model to call bash mkdir instead.
  await mkdir(dirname(resolved), { recursive: true });
  await writeFile(resolved, content, "utf8");
  return {
    path: relative(worktreeRoot(), resolved) || ".",
    bytes: Buffer.byteLength(content, "utf8"),
  };
}

export type EditInput = { path: string; oldText: string; newText: string; replaceAll?: boolean };

export async function editWorktreeFile({ path, oldText, newText, replaceAll }: EditInput) {
  const resolved = resolveInside(path);
  const before = await readFile(resolved, "utf8");

  const count = occurrences(before, oldText);
  if (count === 0) {
    throw new Error(`oldText was not found in ${path}`);
  }
  // An ambiguous edit is refused rather than guessed: replacing the first of several
  // identical blocks is how an agent silently changes the wrong one.
  if (count > 1 && !replaceAll) {
    throw new Error(
      `oldText appears ${count} times in ${path} - include more context to make it unique, ` +
        `or pass replaceAll`,
    );
  }

  const after = replaceAll ? before.split(oldText).join(newText) : before.replace(oldText, newText);
  await writeFile(resolved, after, "utf8");

  return {
    path: relative(worktreeRoot(), resolved) || ".",
    replaced: replaceAll ? count : 1,
  };
}

function occurrences(haystack: string, needle: string): number {
  if (needle === "") return 0;
  let count = 0;
  let at = haystack.indexOf(needle);
  while (at !== -1) {
    count += 1;
    at = haystack.indexOf(needle, at + needle.length);
  }
  return count;
}
